# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a41776f820627b342bc2586de3eba62e09dc144d1b2b52c9c25f7ec30286d4e3dabe5455a4497fdab34e00978ef0b683a110d788445cb055315b42197c77ebd

test:
  secret_key_base: 8269b1fa34d24393095226beaa6850352c732bb4e3fbb40af7b85212768ce13cf2dc824c3d25a6469ed292abedf3ba4bdf3c9bf0d7c0844eda5d5a6b373506c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
