# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73be1868a420052078eb5242ee062a8fe383c7fa47d1dca05dae750200b99ad51c42986eccd713d1f17fdccb56f065e7d49b4cec4752ecb36df0933fd7ffdb64

test:
  secret_key_base: 86d5a7a471ad217510d88e5a4125dba77a4155c8c881eb1112675e940272b0be0348f666b6bbcfec8c4bbc67ba37ca51e8a86fdb9b5ca6f445d36e35154f7f44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
